<?php
return array (
  'app' => 'Admin',
  'model' => 'Financial',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '财务管理',
  'icon' => 'money',
  'remark' => '',
  'listorder' => '4',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Financial',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '提现列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Financial',
      'action' => 'recharge_add',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '会员充值',
      'icon' => '',
      'remark' => '',
      'listorder' => '2',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Financial',
          'action' => 'recharge_add_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '提交添加',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Financial',
      'action' => 'recharge_list',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '充值记录',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
    ),
  ),
);