<?php
return array (
  'app' => 'Admin',
  'model' => 'Goods',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '商品管理',
  'icon' => 'inbox',
  'remark' => '',
  'listorder' => '3',
  'children' => 
  array (
    array (
      'app' => 'Goods',
      'model' => 'AdminGoods',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商品列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Goods',
          'model' => 'AdminGoods',
          'action' => 'listorders',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '商品排序',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminGoods',
          'action' => 'top',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '商品置顶',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminGoods',
          'action' => 'recommend',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '商品推荐',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminGoods',
          'action' => 'move',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '批量移动',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminGoods',
          'action' => 'check',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '商品审核',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminGoods',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除商品',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminGoods',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑商品',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminGoods',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加商品',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Goods',
      'model' => 'AdminCategory',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商品分类',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Goods',
          'model' => 'AdminCategory',
          'action' => 'listorders',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '分类排序',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminCategory',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除分类',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminCategory',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑分类',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Goods',
          'model' => 'AdminCategory',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加分类',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
  ),
);