<?php
return array (
  'app' => 'Admin',
  'model' => 'Agent',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '0',
  'name' => '报单中心',
  'icon' => 'inbox',
  'remark' => '',
  'listorder' => '2',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '中心列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Agent',
          'action' => 'check',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '中心审核',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Agent',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除中心',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'add',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '添加中心',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Agent',
          'action' => 'add_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '提交添加',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Randprice',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '报单价格',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);